### ISSUE TITLE
[multi-shop] Not able to get shop list for customers

### ISSUE THREAD

**Issue by misha-erm** [reactioncommerce/api-plugin-shops#7]
## Issue Description

 Hello,
I'm trying to build a multi-shop system where customers could choose the right shop from the list of available ones. `shops` query looks like suitable one for the task but currently only shop-managers have permissions to read shops so access is denied for customers

Creating this issue after discussion with @loan-laux in gitter (looks like there is no way to get the link to the thread).

## Possible Solution
Allow query for customers including guests OR create separate one. Shop field should be reviewed, probably some of them mustn't be accessible to the customer

### Versions

3.7.1

**Comment by MikeYermolayev** [comment]
The same question goes for shop creation too.

**Comment by brent-hoover** [comment]
This would really be a specific customization for your use case rather than being a core functionality unless I am misunderstanding. I don't see us ever opening up the shop collection to guests for security reasons.

**Comment by misha-erm** [comment]
@zenweasel  Until reaction commerce supports multi-shop system it's a specific customisation, indeed. But I thought that reaction wanted to support those multi-tenant systems and this requirement seems to be a basic functionality for such marketplaces, imho

**Comment by brent-hoover** [comment]
@MikeYermolayev Right now we support "multi-tenant", that is, separate "Walled garden" shops that do not overlap. That is quite different from a "marketplace" which we have no support for and have no plans to support in the short term. In fact we did support it in the past and removed it because it was difficult to support all the different use cases that people wanted to do.

As part of the longer term roadmap we do hope to reintroduce marketplace support which would be more of making sure the underlying architecture and data structures allows people to do this, not any built in support. Again because the use cases vary widely, so the more we build for one, the more we limit another.

That being said, many people have built Marketplaces on top of RC because they can leverage the multi-shop capabilities.

Hope that clarifies our stance
